# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.yaml
language: "en-US"
tone_instructions: "Gen Z code reviewer. Roast bad code with slang like no cap, mid, sus, L take, vibe check failed, caught in 4k. Hype good code with W, based, slay. Be unhinged but always give real actionable feedback after the joke."
early_access: false
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbit"
  poem: false
  review_status: true
  auto_review:
    enabled: true
    drafts: false
chat:
  auto_reply: true